<a href="https://colab.research.google.com/github/AsadovDovud/Final_project/blob/main/cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [135]:
import pandas as pd
import numpy as np

In [136]:
df = pd.read_csv("/content/automobile_data_nan.csv", index_col="index")
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0

In [137]:
df.isnull()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,False,False,False,False,False,False,True,False,False
1,False,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...
81,False,False,False,False,False,False,False,False,False
82,False,False,True,False,True,False,False,False,False
86,False,False,False,True,False,False,False,True,False
87,False,False,False,False,True,False,False,False,False
88,False,False,False,False,False,False,True,False,False

In [138]:
df.notnull()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,True,True,True,True,True,True,False,True,True
1,True,True,False,True,True,True,True,True,True
2,True,True,True,True,True,True,True,False,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,False,False,True
...,...,...,...,...,...,...,...,...,...
81,True,True,True,True,True,True,True,True,True
82,True,True,False,True,False,True,True,True,True
86,True,True,True,False,True,True,True,False,True
87,True,True,True,True,False,True,True,True,True
88,True,True,True,True,True,True,False,True,True

In [139]:
df.isnull().sum()

company              0
body-style           0
wheel-base          15
length              13
engine-type         12
num-of-cylinders     0
horsepower          16
average-mileage     15
price                3
dtype: int64

In [140]:
len(df)

61

In [141]:
df.isnull().sum()/len(df)*100

company              0.000000
body-style           0.000000
wheel-base          24.590164
length              21.311475
engine-type         19.672131
num-of-cylinders     0.000000
horsepower          26.229508
average-mileage     24.590164
price                4.918033
dtype: float64

In [142]:
df.dropna()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0

In [143]:
len(df.dropna())

14

In [144]:
df.dropna(axis=1)

           company   body-style num-of-cylinders
index
0      alfa-romero  convertible             four
1      alfa-romero  convertible             four
2      alfa-romero    hatchback              six
3             audi        sedan             four
4             audi        sedan             five
...            ...          ...              ...
81      volkswagen        sedan             four
82      volkswagen        sedan             four
86      volkswagen        sedan             four
87           volvo        sedan             four
88           volvo        wagon             four

[61 rows x 3 columns]

In [145]:
df.dropna(axis=1, thresh=48)

           company   body-style  length engine-type num-of-cylinders    price
index
0      alfa-romero  convertible   168.8        dohc             four  13495.0
1      alfa-romero  convertible   168.8        dohc             four  16500.0
2      alfa-romero    hatchback   171.2        ohcv              six  16500.0
3             audi        sedan   176.6         ohc             four  13950.0
4             audi        sedan   176.6         ohc             five  17450.0
...            ...          ...     ...         ...              ...      ...
81      volkswagen        sedan   171.7         ohc             four   7975.0
82      volkswagen        sedan   171.7         NaN             four   7995.0
86      volkswagen        sedan     NaN         ohc             four   9995.0
87           volvo        sedan   188.8         NaN             four  12940.0
88           volvo        wagon   188.8         ohc             four  13415.0

[61 rows x 6 columns]

In [146]:
df.dropna(subset=['price', 'horsepower'])

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
5,audi,sedan,99.8,177.3,ohc,five,110.0,19.0,15250.0
6,audi,wagon,105.8,192.7,ohc,five,110.0,19.0,18920.0
10,bmw,sedan,NaN,176.8,ohc,four,101.0,23.0,16925.0
11,bmw,sedan,101.2,176.8,ohc,six,121.0,NaN,20970.0
14,bmw,sedan,103.5,NaN,ohc,six,182.0,16.0,41315.0
15,bmw,sedan,110.0,197.0,ohc,six,182.0,NaN,36880.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
18,chevrolet,sedan,NaN,158.8,ohc,four,70.0,NaN,6575.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
20,dodge,hatchback,93.7,NaN,ohc,four,68.0,NaN,6229.0
27,honda,wagon,96.5,NaN,ohc,four,76.0,30.0,7295.0
28,honda,sedan,96.5,175.4,ohc,four,101.0,24.0,12945.0
30,isuzu,sedan,NaN,170.7,ohc,four,78.0,24.0,6785.0
34,jaguar,sedan,113.0,199.6,dohc,six,176.0,15.0,35550.0
35,jaguar,sedan,NaN,191.7,ohcv,twelve,262.0,13.0,36000.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
39,mazda,hatchback,NaN,NaN,NaN,two,101.0,17.0,11845.0
44,mercedes-benz,sedan,110.0,190.9,NaN,five,123.0,22.0,25552.0
45,mercedes-benz,wagon,NaN,190.9,ohc,five,123.0,22.0,28248.0
46,mercedes-benz,sedan,120.9,208.1,NaN,eight,184.0,14.0,40960.0
47,mercedes-benz,hardtop,112.0,199.2,NaN,eight,184.0,14.0,45400.0
50,mitsubishi,hatchback,93.7,NaN,NaN,four,68.0,31.0,6189.0
51,mitsubishi,sedan,96.3,172.4,NaN,four,88.0,NaN,6989.0
53,nissan,sedan,NaN,NaN,ohc,four,55.0,NaN,7099.0
54,nissan,sedan,94.5,165.3,ohc,four,69.0,31.0,6649.0
55,nissan,sedan,NaN,165.3,ohc,four,69.0,31.0,6849.0
56,nissan,wagon,94.5,170.2,ohc,four,69.0,31.0,7349.0
57,nissan,sedan,100.4,184.6,ohcv,six,152.0,NaN,13499.0
61,porsche,hardtop,NaN,NaN,NaN,six,207.0,17.0,34028.0
62,porsche,convertible,89.5,168.9,ohcf,six,207.0,17.0,37028.0
66,toyota,hatchback,NaN,158.7,ohc,four,62.0,35.0,5348.0
68,toyota,hatchback,NaN,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,NaN,NaN,four,62.0,27.0,7898.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0

### 1 method
Filling disappeared values with 0

In [147]:
df.fillna(0)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,0.0,21.0,13495.0
1,alfa-romero,convertible,0.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,0.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,0.0,0.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,0.0,171.7,0,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,0.0,ohc,four,100.0,0.0,9995.0
87,volvo,sedan,104.3,188.8,0,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,0.0,23.0,13415.0

### Filling missed walues based on columns not a whole

In [148]:
df.fillna({'horspower':100, 'wheel-base':90})

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,90.0,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,90.0,171.7,NaN,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [149]:
df.fillna({'horsepower':np.mean(df['horsepower'])})

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,108.266667,21.0,13495.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.000000,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.000000,NaN,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.000000,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,108.266667,NaN,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.000000,27.0,7975.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.000000,37.0,7995.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.000000,NaN,9995.0
87,volvo,sedan,104.3,188.8,NaN,four,114.000000,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,108.266667,23.0,13415.0

### Filling missed values with forward values (ffill) or back values (bfill)

In [150]:
df.fillna(method='ffill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,21.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,102.0,24.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100.0,37.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114.0,23.0,13415.0

In [151]:
df.fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111.0,21.0,13495.0
1,alfa-romero,convertible,94.5,168.8,dohc,four,111.0,21.0,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,24.0,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0
4,audi,sedan,99.4,176.6,ohc,five,110.0,19.0,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52.0,37.0,7995.0
86,volkswagen,sedan,97.3,188.8,ohc,four,100.0,23.0,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114.0,23.0,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0

In [152]:
df[df.company=='toyota'].fillna(method='bfill')

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
66,toyota,hatchback,95.7,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6338.0
68,toyota,hatchback,95.7,158.7,ohc,four,62.0,31.0,6488.0
69,toyota,wagon,95.7,169.7,ohc,four,62.0,31.0,6918.0
70,toyota,wagon,95.7,169.7,ohc,four,62.0,27.0,7898.0
71,toyota,wagon,95.7,169.7,ohc,four,156.0,27.0,8778.0
79,toyota,wagon,104.5,187.8,dohc,six,156.0,NaN,15750.0

In [153]:
df.fillna(df.mean()) #numeric_only=True

<ipython-input-153-efcfe6e29a7c>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean()) #numeric_only=True

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.600000,168.800000,dohc,four,108.266667,21.000000,13495.0
1,alfa-romero,convertible,99.219565,168.800000,dohc,four,111.000000,21.000000,16500.0
2,alfa-romero,hatchback,94.500000,171.200000,ohcv,six,154.000000,25.695652,16500.0
3,audi,sedan,99.800000,176.600000,ohc,four,102.000000,24.000000,13950.0
4,audi,sedan,99.400000,176.600000,ohc,five,108.266667,25.695652,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.300000,171.700000,ohc,four,85.000000,27.000000,7975.0
82,volkswagen,sedan,99.219565,171.700000,NaN,four,52.000000,37.000000,7995.0
86,volkswagen,sedan,97.300000,173.852083,ohc,four,100.000000,25.695652,9995.0
87,volvo,sedan,104.300000,188.800000,NaN,four,114.000000,23.000000,12940.0
88,volvo,wagon,104.300000,188.800000,ohc,four,108.266667,23.000000,13415.0

In [154]:
dfh = df[df['body-style']=='hatchback']
dfh

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0
16,chevrolet,hatchback,88.4,141.1,l,three,NaN,47.0,5151.0
17,chevrolet,hatchback,94.5,155.9,ohc,four,70.0,38.0,6295.0
19,dodge,hatchback,93.7,157.3,ohc,four,68.0,31.0,6377.0
20,dodge,hatchback,93.7,NaN,ohc,four,68.0,NaN,6229.0
36,mazda,hatchback,93.1,159.1,NaN,four,NaN,NaN,5195.0
37,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6095.0
38,mazda,hatchback,93.1,159.1,ohc,four,68.0,31.0,6795.0
39,mazda,hatchback,NaN,NaN,NaN,two,101.0,17.0,11845.0
49,mitsubishi,hatchback,NaN,157.3,ohc,four,NaN,37.0,5389.0
50,mitsubishi,hatchback,93.7,NaN,NaN,four,68.0,31.0,6189.0
63,porsche,hatchback,98.4,175.7,dohcv,eight,NaN,NaN,NaN
66,toyota,hatchback,NaN,158.7,ohc,four,62.0,35.0,5348.0
67,toyota,hatchback,95.7,158.7,NaN,four,NaN,31.0,6338.0
68,toyota,hatchback,NaN,158.7,ohc,four,62.0,31.0,6488.0

In [155]:
dfh.fillna(dfh.mean())

<ipython-input-155-ecf55eda71e8>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  dfh.fillna(dfh.mean())

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
2,alfa-romero,hatchback,94.500000,171.200,ohcv,six,154.0,32.727273,16500.000000
16,chevrolet,hatchback,88.400000,141.100,l,three,78.9,47.000000,5151.000000
17,chevrolet,hatchback,94.500000,155.900,ohc,four,70.0,38.000000,6295.000000
19,dodge,hatchback,93.700000,157.300,ohc,four,68.0,31.000000,6377.000000
20,dodge,hatchback,93.700000,159.325,ohc,four,68.0,32.727273,6229.000000
36,mazda,hatchback,93.100000,159.100,NaN,four,78.9,32.727273,5195.000000
37,mazda,hatchback,93.100000,159.100,ohc,four,68.0,31.000000,6095.000000
38,mazda,hatchback,93.100000,159.100,ohc,four,68.0,31.000000,6795.000000
39,mazda,hatchback,93.809091,159.325,NaN,two,101.0,17.000000,11845.000000
49,mitsubishi,hatchback,93.809091,157.300,ohc,four,78.9,37.000000,5389.000000
50,mitsubishi,hatchback,93.700000,159.325,NaN,four,68.0,31.000000,6189.000000
63,porsche,hatchback,98.400000,175.700,dohcv,eight,78.9,32.727273,7159.571429
66,toyota,hatchback,93.809091,158.700,ohc,four,62.0,35.000000,5348.000000
67,toyota,hatchback,95.700000,158.700,NaN,four,78.9,31.000000,6338.000000
68,toyota,hatchback,93.809091,158.700,ohc,four,62.0,31.000000,6488.000000

### .map() and .apply()

This method applies a function that accepts and returns a scalar to every element of a DataFrame.

In [156]:
df['num-of-cylinders'].unique()

array(['four', 'six', 'five', 'three', 'twelve', 'two', 'eight'],
      dtype=object)

In [157]:
dict = {'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'eight':8, 'twelve':12}
df['cylinders'] = df['num-of-cylinders'].map(dict)
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders
index,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5
...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4

In [158]:
kurs = 10720
df['price_uz'] = df['price'].map(lambda x: x*kurs)
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,four,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,four,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,four,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,four,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,four,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,four,NaN,23.0,13415.0,4,143808800.0

### .replace() and .rename()

In [159]:
df.replace('four',4)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,cylinders,price_uz
index,,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,4,NaN,21.0,13495.0,4,144666400.0
1,alfa-romero,convertible,NaN,168.8,dohc,4,111.0,21.0,16500.0,4,176880000.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154.0,NaN,16500.0,6,176880000.0
3,audi,sedan,99.8,176.6,ohc,4,102.0,24.0,13950.0,4,149544000.0
4,audi,sedan,99.4,176.6,ohc,five,NaN,NaN,17450.0,5,187064000.0
...,...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,4,85.0,27.0,7975.0,4,85492000.0
82,volkswagen,sedan,NaN,171.7,NaN,4,52.0,37.0,7995.0,4,85706400.0
86,volkswagen,sedan,97.3,NaN,ohc,4,100.0,NaN,9995.0,4,107146400.0
87,volvo,sedan,104.3,188.8,NaN,4,114.0,23.0,12940.0,4,138716800.0
88,volvo,wagon,104.3,188.8,ohc,4,NaN,23.0,13415.0,4,143808800.0

In [160]:
df2 = pd.read_csv("/content/world_population_duplicates.csv", index_col = 'country')

In [161]:
df2.rename(index=str.upper)

                  rank     density   densityMi    pop2021     area
country
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
BURUNDI             28    440.3044   1140.3884  12255.433    27834
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
NAMIBIA            228      3.1338      8.1166   2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577    611.875   266000
MONGOLIA           230      2.1286      5.5129   3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517      3.533    12173
GREENLAND          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [162]:
df2.rename(columns=str.upper)

                  RANK     DENSITY   DENSITYMI    POP2021     AREA
country
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
Burundi             28    440.3044   1140.3884  12255.433    27834
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
Namibia            228      3.1338      8.1166   2587.344   825615
Western Sahara     229      2.3003      5.9577    611.875   266000
Mongolia           230      2.1286      5.5129   3329.289  1564110
Falkland Islands   231      0.2902      0.7517      3.533    12173
Greenland          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [163]:
df2.rename(index=str.upper, columns=str.upper)

                  RANK     DENSITY   DENSITYMI    POP2021     AREA
country
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
BURUNDI             28    440.3044   1140.3884  12255.433    27834
MACAU                1  21946.4667  56841.3487    658.394       30
MONACO               2  19755.5000  51166.7450     39.511        2
...                ...         ...         ...        ...      ...
NAMIBIA            228      3.1338      8.1166   2587.344   825615
WESTERN SAHARA     229      2.3003      5.9577    611.875   266000
MONGOLIA           230      2.1286      5.5129   3329.289  1564110
FALKLAND ISLANDS   231      0.2902      0.7517      3.533    12173
GREENLAND          232      0.0263      0.0680     56.877  2166086

[247 rows x 5 columns]

In [164]:
df2.rename(columns={'pop2021':'population'}, index={'Macau':'Makao'})

                  rank     density   densityMi  population     area
country
Makao                1  21946.4667  56841.3487     658.394       30
Monaco               2  19755.5000  51166.7450      39.511        2
Burundi             28    440.3044   1140.3884   12255.433    27834
Makao                1  21946.4667  56841.3487     658.394       30
Monaco               2  19755.5000  51166.7450      39.511        2
...                ...         ...         ...         ...      ...
Namibia            228      3.1338      8.1166    2587.344   825615
Western Sahara     229      2.3003      5.9577     611.875   266000
Mongolia           230      2.1286      5.5129    3329.289  1564110
Falkland Islands   231      0.2902      0.7517       3.533    12173
Greenland          232      0.0263      0.0680      56.877  2166086

[247 rows x 5 columns]

### Dublicate

<p>Return boolean values in a series

In [165]:
df2.duplicated()

country
Macau               False
Monaco              False
Burundi             False
Macau                True
Monaco               True
                    ...
Namibia             False
Western Sahara      False
Mongolia            False
Falkland Islands    False
Greenland           False
Length: 247, dtype: bool

In [166]:
df2.duplicated().sum()

15

**drop_duplicates()**
Deleting dublicate values

In [167]:
df2.drop_duplicates()

                  rank     density   densityMi    pop2021     area
country
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
Burundi             28    440.3044   1140.3884  12255.433    27834
Singapore            3   8305.1915  21510.4461   5896.686      710
Hong Kong            4   6841.3134  17719.0017   7552.810     1104
...                ...         ...         ...        ...      ...
Namibia            228      3.1338      8.1166   2587.344   825615
Western Sahara     229      2.3003      5.9577    611.875   266000
Mongolia           230      2.1286      5.5129   3329.289  1564110
Falkland Islands   231      0.2902      0.7517      3.533    12173
Greenland          232      0.0263      0.0680     56.877  2166086

[232 rows x 5 columns]

for finding dublicates not from whole csv but only from mentioned row

In [168]:
df2.drop_duplicates(['rank'])

                  rank     density   densityMi    pop2021     area
country
Macau                1  21946.4667  56841.3487    658.394       30
Monaco               2  19755.5000  51166.7450     39.511        2
Burundi             28    440.3044   1140.3884  12255.433    27834
Singapore            3   8305.1915  21510.4461   5896.686      710
Hong Kong            4   6841.3134  17719.0017   7552.810     1104
...                ...         ...         ...        ...      ...
Namibia            228      3.1338      8.1166   2587.344   825615
Western Sahara     229      2.3003      5.9577    611.875   266000
Mongolia           230      2.1286      5.5129   3329.289  1564110
Falkland Islands   231      0.2902      0.7517      3.533    12173
Greenland          232      0.0263      0.0680     56.877  2166086

[232 rows x 5 columns]

### Guruhlash

In [169]:
df3 = pd.read_csv('/content/world_population.csv', usecols=['country','pop2021', 'area'], index_col='country')
df3

                   pop2021     area
country
Macau              658.394       30
Monaco              39.511        2
Singapore         5896.686      710
Hong Kong         7552.810     1104
Gibraltar           33.698        6
...                    ...      ...
Namibia           2587.344   825615
Western Sahara     611.875   266000
Mongolia          3329.289  1564110
Falkland Islands     3.533    12173
Greenland           56.877  2166086

[232 rows x 2 columns]

**pandas.cut(x, bins, right=True, labels=None, retbins=False, precision=3, include_lowest=False, duplicates='raise', ordered=True)**

In [170]:
bins = [0, 1000, 10000, 30000, 50000, 100000, 300000, 1500000]

In [171]:
population = df3.pop2021

Use cut when you need to segment and sort data values into bins. This function is also useful for going from a continuous variable to a categorical variable. For example, cut could convert ages to groups of age ranges. Supports binning into an equal number of bins, or a pre-specified array of bins.

In [172]:
oraliq = pd.cut(population,bins)
oraliq

country
Macau                   (0, 1000]
Monaco                  (0, 1000]
Singapore           (1000, 10000]
Hong Kong           (1000, 10000]
Gibraltar               (0, 1000]
                        ...
Namibia             (1000, 10000]
Western Sahara          (0, 1000]
Mongolia            (1000, 10000]
Falkland Islands        (0, 1000]
Greenland               (0, 1000]
Name: pop2021, Length: 232, dtype: category
Categories (7, interval[int64, right]): [(0, 1000] < (1000, 10000] < (10000, 30000] <
                                         (30000, 50000] < (50000, 100000] < (100000, 300000] <
                                         (300000, 1500000]]

In [173]:
oraliq.value_counts()

(0, 1000]            72
(1000, 10000]        68
(10000, 30000]       44
(30000, 50000]       19
(50000, 100000]      15
(100000, 300000]     11
(300000, 1500000]     3
Name: pop2021, dtype: int64

In [174]:
df['popBins'] = oraliq

In [175]:
df4 = pd.read_csv('/content/automobile_data.csv', index_col='index')

In [176]:
bins = [0, 10000, 20000, 50000]

In [177]:
range = pd.cut(df.price, bins)

In [178]:
range.value_counts()

(0, 10000]        28
(10000, 20000]    17
(20000, 50000]    13
Name: price, dtype: int64

In [179]:
groups = ["arzon", "o'rta", "qimmat"]
range = pd.cut(df.price, bins, labels=groups)
range.value_counts()

arzon     28
o'rta     17
qimmat    13
Name: price, dtype: int64

In [180]:
range = pd.cut(df.price, 3)
range.value_counts()

(5110.751, 18567.333]     44
(31983.667, 45400.0]       9
(18567.333, 31983.667]     5
Name: price, dtype: int64

In [181]:
range = pd.cut(df.price, 4)
range.value_counts()

(5110.751, 15213.25]    36
(15213.25, 25275.5]     10
(35337.75, 45400.0]      7
(25275.5, 35337.75]      5
Name: price, dtype: int64

**pandas.qcut(x, q, labels=None, retbins=False, precision=3, duplicates='raise')**
Quantile-based discretization function.

Discretize variable into equal-sized buckets based on rank or based on sample quantiles. For example 1000 values for 10 quantiles would produce a Categorical object indicating quantile membership for each data point.

In [182]:
range = pd.qcut(df.price, 3)
range.value_counts()

(5150.999, 7295.0]    20
(7295.0, 16430.0]     19
(16430.0, 45400.0]    19
Name: price, dtype: int64

In [183]:
range = pd.qcut(df.horsepower, 3)
range.value_counts()

(51.999, 70.0]    18
(112.0, 262.0]    15
(70.0, 112.0]     12
Name: horsepower, dtype: int64

### .groupby()

In [184]:
df4.groupby('company').mean()

<ipython-input-184-4bc838971b82>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df4.groupby('company').mean()

,wheel-base,length,horsepower,average-mileage,price
company,,,,,
alfa-romero,90.566667,169.600000,125.333333,20.333333,15498.333333
audi,101.200000,180.800000,109.250000,20.000000,16392.500000
bmw,103.433333,185.033333,144.833333,19.000000,27213.333333
chevrolet,92.466667,151.933333,62.666667,41.000000,6007.000000
dodge,93.700000,157.300000,68.000000,31.000000,6303.000000
honda,96.500000,167.200000,92.333333,26.333333,10195.000000
isuzu,94.433333,160.833333,72.666667,33.333333,6785.000000
jaguar,109.333333,196.966667,204.666667,14.333333,34600.000000
mazda,95.900000,164.260000,75.400000,28.000000,9654.800000
mercedes-benz,113.225000,197.275000,153.500000,18.000000,35040.000000
mitsubishi,95.000000,164.850000,78.000000,29.500000,6689.000000
nissan,95.680000,170.140000,82.800000,31.400000,8289.000000
porsche,92.466667,171.166667,234.000000,17.000000,35528.000000
toyota,96.957143,167.571429,75.428571,28.714286,8216.857143
volkswagen,97.300000,171.700000,72.250000,31.750000,8435.000000
volvo,104.300000,188.800000,114.000000,23.000000,13177.500000

In [185]:
df4.groupby('company').price.mean()

company
alfa-romero      15498.333333
audi             16392.500000
bmw              27213.333333
chevrolet         6007.000000
dodge             6303.000000
honda            10195.000000
isuzu             6785.000000
jaguar           34600.000000
mazda             9654.800000
mercedes-benz    35040.000000
mitsubishi        6689.000000
nissan            8289.000000
porsche          35528.000000
toyota            8216.857143
volkswagen        8435.000000
volvo            13177.500000
Name: price, dtype: float64

In [186]:
df.groupby(['company','body-style']).mean()

<ipython-input-186-22666974c88d>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['company','body-style']).mean()

                           wheel-base      length  horsepower  \
company       body-style
alfa-romero   convertible   88.600000  168.800000  111.000000
              hatchback     94.500000  171.200000  154.000000
audi          sedan         99.666667  176.833333  106.000000
              wagon        105.800000  192.700000  110.000000
bmw           sedan        103.880000  184.900000  146.500000
chevrolet     hatchback     91.450000  148.500000   70.000000
              sedan               NaN  158.800000   70.000000
dodge         hatchback     93.700000  157.300000   68.000000
honda         sedan         96.500000  172.250000  101.000000
              wagon         96.500000         NaN   76.000000
isuzu         sedan         94.500000  163.300000   72.666667
jaguar        sedan        113.000000  195.650000  219.000000
mazda         hatchback     93.100000  159.100000   79.000000
              sedan        104.900000  175.000000         NaN
mercedes-benz hardtop      112.000000  199.200000  184.000000
              sedan        115.450000  199.500000  153.500000
              wagon               NaN  190.900000  123.000000
mitsubishi    hatchback     93.700000  157.300000   68.000000
              sedan         96.300000  172.400000   88.000000
nissan        sedan         97.450000  171.733333   86.250000
              wagon         94.500000  170.200000   69.000000
porsche       convertible   89.500000  168.900000  207.000000
              hardtop             NaN         NaN  207.000000
              hatchback     98.400000  175.700000         NaN
toyota        hatchback     95.700000  158.700000   62.000000
              wagon         97.900000  175.733333   93.333333
volkswagen    sedan         97.300000  171.700000   79.000000
volvo         sedan        104.300000  188.800000  114.000000
              wagon        104.300000  188.800000         NaN

                           average-mileage         price  cylinders  \
company       body-style
alfa-romero   convertible        21.000000  14997.500000   4.000000
              hatchback                NaN  16500.000000   6.000000
audi          sedan              21.500000  15550.000000   4.666667
              wagon              19.000000  18920.000000   5.000000
bmw           sedan              19.500000  27213.333333   5.333333
chevrolet     hatchback          42.500000   5723.000000   3.500000
              sedan                    NaN   6575.000000   4.000000
dodge         hatchback          31.000000   6303.000000   4.000000
honda         sedan              24.500000  11645.000000   4.000000
              wagon              30.000000   7295.000000   4.000000
isuzu         sedan              31.000000   6785.000000   4.000000
jaguar        sedan              14.333333  34600.000000   8.000000
mazda         hatchback          26.333333   7482.500000   3.500000
              sedan                    NaN  18344.000000   4.000000
mercedes-benz hardtop            14.000000  45400.000000   8.000000
              sedan              18.000000  33256.000000   6.500000
              wagon              22.000000  28248.000000   5.000000
mitsubishi    hatchback          34.000000   5789.000000   4.000000
              sedan              25.000000   7589.000000   4.000000
nissan        sedan              31.000000   8524.000000   4.500000
              wagon              31.000000   7349.000000   4.000000
porsche       convertible        17.000000  37028.000000   6.000000
              hardtop            17.000000  34028.000000   6.000000
              hatchback                NaN           NaN   8.000000
toyota        hatchback          32.333333   6058.000000   4.000000
              wagon              28.333333   9836.000000   4.500000
volkswagen    sedan              33.666667   8435.000000   4.000000
volvo         sedan              23.000000  12940.000000   4.000000
              wagon              23.000000  13415.000000   4.000000

                               price_uz
company       body-style
alfa-romero   convertible  1.607732e+08
              hatchback    1.768800e+08
audi          sedan        1.666960e+08
              wagon        2.028224e+08
bmw           sedan        2.917269e+08
chevrolet     hatchback    6.135056e+07
              sedan        7.048400e+07
dodge         hatchback    6.756816e+07
honda         sedan        1.248344e+08
              wagon        7.820240e+07
isuzu         sedan        7.273520e+07
jaguar        sedan        3.709120e+08
mazda         hatchback    8.021240e+07
              sedan        1.966477e+08
mercedes-benz hardtop      4.866880e+08
              sedan        3.565043e+08
              wagon        3.028186e+08
mitsubishi    hatchback    6.205808e+07
              sedan        8.135408e+07
nissan        sedan        9.137728e+07
              wagon        7.878128e+07
porsche       convertible  3.969402e+08
              hardtop      3.647802e+08
              hatchback             NaN
toyota        hatchback    6.494176e+07
              wagon        1.054419e+08
volkswagen    sedan        9.042320e+07
volvo         sedan        1.387168e+08
              wagon        1.438088e+08

In [187]:
df4.groupby('company').agg([min, max, np.mean])

<ipython-input-187-9addc5080843>:1: FutureWarning: ['body-style', 'engine-type', 'num-of-cylinders'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df4.groupby('company').agg([min, max, np.mean])

              wheel-base                    length                     \
                     min    max        mean    min    max        mean
company
alfa-romero         88.6   94.5   90.566667  168.8  171.2  169.600000
audi                99.4  105.8  101.200000  176.6  192.7  180.800000
bmw                101.2  110.0  103.433333  176.8  197.0  185.033333
chevrolet           88.4   94.5   92.466667  141.1  158.8  151.933333
dodge               93.7   93.7   93.700000  157.3  157.3  157.300000
honda               96.5   96.5   96.500000  157.1  175.4  167.200000
isuzu               94.3   94.5   94.433333  155.9  170.7  160.833333
jaguar             102.0  113.0  109.333333  191.7  199.6  196.966667
mazda               93.1  104.9   95.900000  159.1  175.0  164.260000
mercedes-benz      110.0  120.9  113.225000  190.9  208.1  197.275000
mitsubishi          93.7   96.3   95.000000  157.3  172.4  164.850000
nissan              94.5  100.4   95.680000  165.3  184.6  170.140000
porsche             89.5   98.4   92.466667  168.9  175.7  171.166667
toyota              95.7  104.5   96.957143  158.7  187.8  167.571429
volkswagen          97.3   97.3   97.300000  171.7  171.7  171.700000
volvo              104.3  104.3  104.300000  188.8  188.8  188.800000

              horsepower                  average-mileage                 \
                     min  max        mean             min max       mean
company
alfa-romero          111  154  125.333333              19  21  20.333333
audi                 102  115  109.250000              18  24  20.000000
bmw                  101  182  144.833333              15  23  19.000000
chevrolet             48   70   62.666667              38  47  41.000000
dodge                 68   68   68.000000              31  31  31.000000
honda                 76  101   92.333333              24  30  26.333333
isuzu                 70   78   72.666667              24  38  33.333333
jaguar               176  262  204.666667              13  15  14.333333
mazda                 68  101   75.400000              17  31  28.000000
mercedes-benz        123  184  153.500000              14  22  18.000000
mitsubishi            68   88   78.000000              25  37  29.500000
nissan                55  152   82.800000              19  45  31.400000
porsche              207  288  234.000000              17  17  17.000000
toyota                62  156   75.428571              19  35  28.714286
volkswagen            52  100   72.250000              26  37  31.750000
volvo                114  114  114.000000              23  23  23.000000

                 price
                   min      max          mean
company
alfa-romero    13495.0  16500.0  15498.333333
audi           13950.0  18920.0  16392.500000
bmw            16430.0  41315.0  27213.333333
chevrolet       5151.0   6575.0   6007.000000
dodge           6229.0   6377.0   6303.000000
honda           7295.0  12945.0  10195.000000
isuzu           6785.0   6785.0   6785.000000
jaguar         32250.0  36000.0  34600.000000
mazda           5195.0  18344.0   9654.800000
mercedes-benz  25552.0  45400.0  35040.000000
mitsubishi      5389.0   8189.0   6689.000000
nissan          6649.0  13499.0   8289.000000
porsche        34028.0  37028.0  35528.000000
toyota          5348.0  15750.0   8216.857143
volkswagen      7775.0   9995.0   8435.000000
volvo          12940.0  13415.0  13177.500000

In [188]:
df4.groupby('company').agg([min, max, lambda x: np.median(x)])

<ipython-input-188-9f04783163df>:1: FutureWarning: ['body-style', 'engine-type', 'num-of-cylinders'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df4.groupby('company').agg([min, max, lambda x: np.median(x)])

              wheel-base                   length                    \
                     min    max <lambda_0>    min    max <lambda_0>
company
alfa-romero         88.6   94.5      88.60  168.8  171.2     168.80
audi                99.4  105.8      99.80  176.6  192.7     176.95
bmw                101.2  110.0     102.35  176.8  197.0     182.90
chevrolet           88.4   94.5      94.50  141.1  158.8     155.90
dodge               93.7   93.7      93.70  157.3  157.3     157.30
honda               96.5   96.5      96.50  157.1  175.4     169.10
isuzu               94.3   94.5      94.50  155.9  170.7     155.90
jaguar             102.0  113.0     113.00  191.7  199.6     199.60
mazda               93.1  104.9      93.10  159.1  175.0     159.10
mercedes-benz      110.0  120.9     111.00  190.9  208.1     195.05
mitsubishi          93.7   96.3      95.00  157.3  172.4     164.85
nissan              94.5  100.4      94.50  165.3  184.6     165.30
porsche             89.5   98.4      89.50  168.9  175.7     168.90
toyota              95.7  104.5      95.70  158.7  187.8     169.70
volkswagen          97.3   97.3      97.30  171.7  171.7     171.70
volvo              104.3  104.3     104.30  188.8  188.8     188.80

              horsepower                 average-mileage                 \
                     min  max <lambda_0>             min max <lambda_0>
company
alfa-romero          111  154      111.0              19  21       21.0
audi                 102  115      110.0              18  24       19.0
bmw                  101  182      151.5              15  23       18.5
chevrolet             48   70       70.0              38  47       38.0
dodge                 68   68       68.0              31  31       31.0
honda                 76  101      100.0              24  30       25.0
isuzu                 70   78       70.0              24  38       38.0
jaguar               176  262      176.0              13  15       15.0
mazda                 68  101       68.0              17  31       31.0
mercedes-benz        123  184      153.5              14  22       18.0
mitsubishi            68   88       78.0              25  37       28.0
nissan                55  152       69.0              19  45       31.0
porsche              207  288      207.0              17  17       17.0
toyota                62  156       62.0              19  35       31.0
volkswagen            52  100       68.5              26  37       32.0
volvo                114  114      114.0              23  23       23.0

                 price
                   min      max <lambda_0>
company
alfa-romero    13495.0  16500.0    16500.0
audi           13950.0  18920.0    16350.0
bmw            16430.0  41315.0    25865.0
chevrolet       5151.0   6575.0     6295.0
dodge           6229.0   6377.0     6303.0
honda           7295.0  12945.0    10345.0
isuzu           6785.0   6785.0        NaN
jaguar         32250.0  36000.0    35550.0
mazda           5195.0  18344.0     6795.0
mercedes-benz  25552.0  45400.0    34604.0
mitsubishi      5389.0   8189.0     6589.0
nissan          6649.0  13499.0     7099.0
porsche        34028.0  37028.0        NaN
toyota          5348.0  15750.0     6918.0
volkswagen      7775.0   9995.0     7985.0
volvo          12940.0  13415.0    13177.5